cors:
  originPatterns: http://localhost:3000, http://localhost:8080, https://mrblog-joosecj.netlify.app, http://localhost:5173

spring:
  application:
    name: MRBlog
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

springdoc:
  paths-to-match:
    - /api/**/v1/**
    - /oauth/**
  swagger-ui:
    use-root-path: true
server:
  forward-headers-strategy: framework