
INSERT INTO tb_user (name, email, password, birth_date, url_image, registration_date, account_non_expired, account_non_locked, credentials_non_expired, enabled) VALUES ('Antonio Carlos', 'antonio@gmail.com', 'c0d6b7b7a97ac701f5466a38e317e49f2647f99b9f2f1e9a9f2c652a73e3ac0a60644e0f25db642f', '1990-05-17',  'https://avatars.githubusercontent.com/u/109112608?v=4', '2022-10-01', 1, 1, 1, 1);
INSERT INTO tb_user (name, email, password, birth_date, url_image, registration_date, account_non_expired, account_non_locked, credentials_non_expired, enabled) VALUES ('Clara Rita', 'rita@gmail.com', 'c0d6b7b7a97ac701f5466a38e317e49f2647f99b9f2f1e9a9f2c652a73e3ac0a60644e0f25db642f', '1998-10-07',  'https://avatars.githubusercontent.com/u/109112608?v=4', '2023-01-15', 1, 1, 1, 1);

INSERT INTO tb_permission (description) VALUES ('ADMIN');
INSERT INTO tb_permission (description) VALUES  ('MANAGER');
INSERT INTO tb_permission (description) VALUES ('COMMON_USER');

-- INSERT INTO tb_user (name, email, birth_date, url_image, registration_date) VALUES ('Antonio Carlos', 'antonio@gmail.com', '1990-05-17',  'https://avatars.githubusercontent.com/u/109112608?v=4', '2022-10-01');
-- INSERT INTO tb_user (name, email, birth_date, url_image, registration_date) VALUES ('Clara Rita', 'rita@gmail.com', '1980-05-17',  'https://avatars.githubusercontent.com/u/109112608?v=4', '2022-10-01');

INSERT INTO tb_category (name, description) VALUES ('Economia', 'The standard chunk');
INSERT INTO tb_category (name, description) VALUES ('Esporte', 'Contrary to popular');


INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Traders de criptomoedas mudam seu foco para altcoins enquanto o preço', 'But I must explain to you how all this mistaken', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem natus excepturi itaque voluptates. Sit doloremque veritatis neque iure blanditiis ab ea voluptas, reiciendis eaque ratione dolores, magnam asperiores beatae atque unde cupiditate quod adipisci rem voluptatibus laboriosam suscipit minus non placeat! Aliquam, cumque. Blanditiis officiis, et aut voluptatibus facere ullam dolorum reiciendis dolorem inventore quidem error, voluptatem cum accusantium deserunt voluptates numquam enim dicta modi dolor aliquid minus, mollitia voluptate totam vitae. Nam iste totam voluptatibus maiores dolorum, ab nisi placeat odit dolore porro deleniti iure facere rem earum, rerum vero facilis, aspernatur deserunt cum eos corporis laboriosam? Quo, sapiente.', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Que na bolsa de valores', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Dificuldade para minerar Bitcoin atinge nível mais alto da história da cripto', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Bitcoin: O que é, Como Funciona, Calculadora | Foxbit', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 1);

INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Notícias Índice Dólar | Noticias Indice Dolar ', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Dólar hoje: moeda opera em queda, com agenda fraca ', 'At vero eos et accusamus et iusto odio dignissimos', 'ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Dólar Americano - USD Taxas de Câmbio - Wise', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Dólar Turismo: Cotação de Hoje, Gráficos e tabelas', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 1);

INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Índice de sentimento do investidor na Zona do Euro', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Euro Hoje: confira a cotação | Travelex Confidence', 'At vero eos et accusamus et iusto odio dignissimos','ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditateet iusto odio dignissimos ducimus qui blanditiis',TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Euro hoje: qual o valor do euro para real hoje, 05 de outubro', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 1);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('O Grande Debate: veja se vale a pena investir em euro ou libra agora', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 1);


INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Palmeiras escalado: atenção para o horário diferente', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('América-MG atropela no início, vence Fluminense', 'At vero eos et accusamus et iusto odio dignissimos ducimus', 'blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditateblanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Cássio será titular contra o Flamengo na final da Copa do Brasil', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Jogador do Ceará deixa o Mineirão de ambulância após bolada', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 2);

INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Ídolo da Fiel, Elias se aposentou discretamente e hoje', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Pelé fica em quarto em ranking dos 100 melhores ', 'At vero eos et accusamus et iusto odio dignissimos', 'ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 2, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Lucas Barbosa desbanca Luan e será titular do Santos', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 2);
INSERT INTO tb_post (title, title_description, description, date_time, user_id, category_id) VALUES ('Vasco tem dois desfalques e conta com um retorno certo', 'But I must explain to you how all this mistaken', 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate', TIMESTAMP WITH TIME ZONE '2022-10-06', 1, 2);


INSERT INTO tb_comment (comment_description, date_Time, post_id, user_id) VALUES ('provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita', TIMESTAMP WITH TIME ZONE '2022-07-26', 1, 1);
INSERT INTO tb_comment (comment_description, date_Time, post_id, user_id) VALUES ('rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae', TIMESTAMP WITH TIME ZONE '2022-07-27', 1, 2);

INSERT INTO tb_comment (comment_description, date_Time, post_id, user_id) VALUES ('but because those who do not know how to pursue pleasure', TIMESTAMP WITH TIME ZONE '2022-07-28', 2, 2);
INSERT INTO tb_comment (comment_description, date_Time, post_id, user_id) VALUES ('chooses to enjoy a pleasure that has no annoying consequences, or one who avoids', TIMESTAMP WITH TIME ZONE '2022-07-26', 2, 1);